// Package frontend embeds the built SvelteKit admin SPA.
// The build/ directory is generated by running `pnpm build` in this directory.
package frontend

import (
	"embed"
	"io"
	"io/fs"
	"net/http"
)

//go:embed all:build
var buildFS embed.FS

// FaviconHandler serves the embedded SVG or ICO favicon so the public
// server-rendered pages and the admin SPA share a single favicon source — change
// frontend/static/favicon.svg, rebuild, and every page updates.
func FaviconHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		name, contentType := "favicon.svg", "image/svg+xml"
		if r.URL.Path == "/favicon.ico" {
			name, contentType = "favicon.ico", "image/x-icon"
		}
		f, err := buildFS.Open("build/" + name)
		if err != nil {
			http.NotFound(w, r)
			return
		}
		defer f.Close()
		w.Header().Set("Content-Type", contentType)
		w.Header().Set("Cache-Control", "public, max-age=3600")
		_, _ = io.Copy(w, f)
	})
}

// Handler returns an HTTP handler that serves the built admin SPA.
// Paths not matching a real file fall back to 200.html so that
// client-side routing works for all /admin/* subroutes.
func Handler() http.Handler {
	sub, err := fs.Sub(buildFS, "build")
	if err != nil {
		panic("frontend: fs.Sub: " + err.Error())
	}
	return &spaHandler{fs: http.FS(sub)}
}

type spaHandler struct {
	fs http.FileSystem
}

func (h *spaHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	f, err := h.fs.Open(r.URL.Path)
	if err == nil {
		st, statErr := f.Stat()
		f.Close() // #nosec G104 -- handle already Stat()-ed above; nothing actionable on close error
		// Treat directories as not-found so the SPA shell handles the route
		// instead of http.FileServer rendering a directory listing.
		if statErr == nil && st.IsDir() {
			err = fs.ErrNotExist
		}
	}
	if err != nil {
		r2 := *r
		r2.URL.Path = "/200.html"
		http.FileServer(h.fs).ServeHTTP(w, &r2)
		return
	}
	http.FileServer(h.fs).ServeHTTP(w, r)
}
